title: Procrastination log
description: Ryan's wasted time lol
theme: just-the-docs

url: https://rshi07.github.io/the-stuff-i-do-instead-of-work/

aux_links:
  Template Repository: https://github.com/rshi07/the-stuff-i-do-instead-of-work/

plugins:
  - jekyll-default-layout
